### ISSUE TITLE
Release artifacts are text files containing a path rather than an actual .tar.gz

### ISSUE THREAD

**Issue by smashwilson** [bchr02/node-pre-gyp-github#29]
Using node-pre-gyp-github >= 1.4.0, it appears that the release artifacts that are published to GitHub are _text files containing the path to the tarball_ rather than the tarball itself:

```
$ cat ~/Downloads/watcher-v1.1.3-node-v51-darwin-x64.tar.gz
/Users/distiller/project/build/stage/1.1.3/watcher-v1.1.3-node-v51-darwin-x64.tar.gz
```

My guess is that octokit's `uploadAsset()` function is now expecting something like a File object rather than a path for its `file` option?

**Comment by tuananh** [comment]
i got the same issue as well

**Comment by tylerssn** [comment]
Same here.

**Comment by bchr02** [comment]
@smashwilson thanks for reporting this. Any chance you could send a pull request?

**Comment by tylerssn** [comment]
For those who are waiting for the PR to be accepted or can't upgrade for whatever reason after it is accepted, I am using Appveyor and Travis CI built-in mechanism for uploading:

```yaml
#.travis.yml

deploy:
  provider: releases
  name: v${TRAVIS_TAG}
  api_key: ${NODE_PRE_GYP_GITHUB_TOKEN}
  file_glob: true
  # This is the relevant upload line for Travis CI
  file: build/stage/*/*.gz
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
```

```yaml
#appveyor.yml

artifacts:
  - path: build/stage/*/*.gz
    name: build addon

deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: v$(APPVEYOR_REPO_TAG_NAME)
    description: v$(APPVEYOR_REPO_TAG_NAME)
    auth_token: $(NODE_PRE_GYP_GITHUB_TOKEN)
    # Get a gz file from the artifacts
    artifact: /.*\.gz/
    draft: false
    prerelease: false
    force_update: true
    on:
      appveyor_repo_tag: true
```
